MODEL:
  META_ARCHITECTURE: "AttrBaseline"

  BACKBONE:
    NAME: "build_resnet_backbone"
    NORM: "BN"
    DEPTH: "50x"
    LAST_STRIDE: 2
    FEAT_DIM: 2048
    WITH_IBN: False
    PRETRAIN: True
    PRETRAIN_PATH: "/export/home/lxy/.cache/torch/checkpoints/resnet50-19c8e357.pth"

  HEADS:
    NAME: "AttrHead"
    NORM: "BN"
    WITH_BNNECK: True
    POOL_LAYER: "fastavgpool"
    CLS_LAYER: "linear"
    NUM_CLASSES: 26

  LOSSES:
    NAME: ("BinaryCrossEntropyLoss",)

    BCE:
      WEIGHT_ENABLED: True
      SCALE: 1.

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  REA:
    ENABLED: False
  DO_PAD: True

DATALOADER:
  NUM_WORKERS: 8

SOLVER:
  OPT: "SGD"
  MAX_ITER: 30
  BASE_LR: 0.01
  BIAS_LR_FACTOR: 2.
  HEADS_LR_FACTOR: 10.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  SCHED: "WarmupCosineAnnealingLR"
  DELAY_ITERS: 5
  ETA_MIN_LR: 0.00001

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 5

  CHECKPOINT_PERIOD: 10

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 256

CUDNN_BENCHMARK: True

