MODEL:
  META_ARCHITECTURE: 'PartialBaseline'

  BACKBONE:
    NAME: "build_resnet_backbone"
    DEPTH: "50x"
    NORM: "BN"
    LAST_STRIDE: 1
    WITH_IBN: True
    PRETRAIN_PATH: "/export/home/lxy/.cache/torch/checkpoints/resnet50_ibn_a-d9d0bb7b.pth"

  HEADS:
    NAME: "DSRHead"
    NORM: "BN"
    POOL_LAYER: "avgpool"
    NECK_FEAT: "before"
    CLS_LAYER: "linear"

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss")
    CE:
      EPSILON: 0.1
      SCALE: 1.
    TRI:
      MARGIN: 0.3
      HARD_MINING: False
      SCALE: 1.

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("PartialREID", "PartialiLIDS","OccludedREID",)

INPUT:
  SIZE_TRAIN: [384, 128]
  SIZE_TEST: [384, 128]
  REA:
    ENABLED: False
  DO_PAD: False

DATALOADER:
  PK_SAMPLER: True
  NAIVE_WAY: False
  NUM_INSTANCE: 4
  NUM_WORKERS: 8
  
SOLVER:
  OPT: "Adam" 
  MAX_ITER: 30
  BASE_LR: 0.00035 
  BIAS_LR_FACTOR: 2. 
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0
  IMS_PER_BATCH: 64 

  SCHED: "WarmupMultiStepLR"
  STEPS: [15, 25]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 5

  CHECKPOINT_PERIOD: 10

TEST:
  EVAL_PERIOD: 5
  IMS_PER_BATCH: 128

CUDNN_BENCHMARK: True

OUTPUT_DIR: "projects/PartialReID/logs/test_partial"
