_BASE_: "../Base-bagtricks.yml"

MODEL:
  BACKBONE:
    WITH_IBN: False
    EXTRA_BN: False
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  HEADS:
    NAME: "EmbeddingHead"
    NORM: "BN"
    EMBEDDING_DIM: 1024
    WITH_BNNECK: True
    POOL_LAYER: "avgpool"
    NECK_FEAT: "after"
    CLS_LAYER: "linear"
  LOSSES:
    NAME: ("CrossEntropyLoss",)
    CE:
      EPSILON: 0.1
      SCALE: 1.0

INPUT:
  REA:
    MEAN: [0.0, 0.0, 0.0]
    

DATALOADER:
  PK_SAMPLER: False

SOLVER:
  MAX_ITER: 60
  STEPS: [40, 90]
  HEADS_LR_FACTOR: 1.0
  BACKBONE_BN_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: -1

TEST:
  EVAL_PERIOD: 30
  IMS_PER_BATCH: 128

DATASETS:
  NAMES: ("CMDM",)
  TESTS: ("CMDM",)
  KWARGS: 'data_name:duke+split_mode:id+split_ratio:1.0'
  ROOT: "/home/dengpanfu/data"

OUTPUT_DIR: "logs/cmdm/ide_R50"
