_BASE_: "../Base-Strongerbaseline.yml"

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

MODEL:
  BACKBONE:
    WITH_IBN: True

SOLVER:
  OPT: "SGD"
  BASE_LR: 0.01
  ETA_MIN_LR: 7.7e-5

  IMS_PER_BATCH: 64
  MAX_ITER: 60
  DELAY_ITERS: 30
  WARMUP_ITERS: 10
  FREEZE_ITERS: 10

  CHECKPOINT_PERIOD: 20

DATASETS:
  NAMES: ("VeRi",)
  TESTS: ("VeRi",)

TEST:
  EVAL_PERIOD: 20
  IMS_PER_BATCH: 128

OUTPUT_DIR: "logs/veri/sbs_R50-ibn"
