MODEL:
  META_ARCHITECTURE: "Baseline"

  FREEZE_LAYERS: ["backbone"]

  BACKBONE:
    NAME: "build_resnet_backbone"
    DEPTH: "34x"
    LAST_STRIDE: 1
    FEAT_DIM: 512
    NORM: "BN"
    WITH_NL: False
    WITH_IBN: True
    PRETRAIN: True
    PRETRAIN_PATH: "/export/home/lxy/.cache/torch/checkpoints/resnet34_ibn_a-94bc1577.pth"

  HEADS:
    NAME: "EmbeddingHead"
    NORM: "BN"
    NECK_FEAT: "after"
    EMBEDDING_DIM: 0
    POOL_LAYER: "gempool"
    CLS_LAYER: "circleSoftmax"
    SCALE: 64
    MARGIN: 0.35

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss",)

    CE:
      EPSILON: 0.1
      SCALE: 1.

    TRI:
      MARGIN: 0.0
      HARD_MINING: True
      NORM_FEAT: False
      SCALE: 1.

    CIRCLE:
      MARGIN: 0.25
      ALPHA: 96
      SCALE: 1.0

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  DO_AUTOAUG: True
  REA:
    ENABLED: True
  CJ:
    ENABLED: True
  DO_PAD: True

DATALOADER:
  PK_SAMPLER: True
  NAIVE_WAY: False
  NUM_INSTANCE: 16
  NUM_WORKERS: 8

SOLVER:
  AMP_ENABLED: False
  OPT: "Adam"
  SCHED: "WarmupCosineAnnealingLR"
  MAX_ITER: 60
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0
  IMS_PER_BATCH: 64

  DELAY_ITERS: 30
  ETA_MIN_LR: 0.00000077

  FREEZE_ITERS: 5

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 5

  CHECKPOINT_PERIOD: 100

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 256

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)
  COMBINEALL: False

CUDNN_BENCHMARK: True

OUTPUT_DIR: "projects/HPOReID/logs/dukemtmc/r34-ibn_bohb_bsz_num-inst"
