_BASE_: "../../../../configs/Base-bagtricks.yml"

MODEL:
  BACKBONE:
    DEPTH: "50x"
    WITH_IBN: True

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

OUTPUT_DIR: "projects/DistillReID/logs/dukemtmc/bagtricks_R50-ibn"