_BASE_: "../Base-bot-kd.yml"

MODEL_TEACHER:
  BACKBONE:
    DEPTH: "101x"
    FEAT_DIM: 2048

MODEL:
  BACKBONE:
    DEPTH: "18x"
    FEAT_DIM: 512

  STUDENT_WEIGHTS: ""
  TEACHER_WEIGHTS: "projects/DistillReID/logs/dukemtmc/bagtricks_R101-ibn"

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

OUTPUT_DIR: "projects/DistillReID/logs/dukemtmc/bot101ibn-kd-bot18ibn"