_BASE_: "../../../configs/Base-Strongerbaseline.yml"

MODEL:
  BACKBONE:
    DEPTH: "18x"
    WITH_IBN: True
    FEAT_DIM: 512

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

OUTPUT_DIR: "projects/DistillReID/logs/dukemtmc/sbs_R18-ibn"