_BASE_: "../../../configs/Base-Strongerbaseline.yml"

MODEL:
  BACKBONE:
    DEPTH: "50x"
    WITH_IBN: True
    FEAT_DIM: 2048

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

OUTPUT_DIR: "projects/DistillReID/logs/dukemtmc/sbs_R50-ibn"